begin;
set local role anon;
do $$ declare a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); c uuid:=gen_random_uuid(); r jsonb; post_id uuid; failed boolean; begin
 r:=public.tripcircle_number_login('0000000099',a);
 if r->>'name_required'<>'true' then raise exception 'New number should request name'; end if;
 r:=public.tripcircle_number_login('0000000099',a,'Number QA');
 if r->>'number_profile'<>'true' or r->>'name'<>'Number QA' then raise exception 'Profile creation failed'; end if;
 perform public.tripcircle_participate(a,'vote',p_destination=>'bordi');
 r:=public.tripcircle_participate(a,'post',p_kind=>'comment',p_body=>'Transactional number profile test');
 post_id:=(r->'post_ids'->>0)::uuid;
 r:=public.tripcircle_number_login('0000000099',b);
 if r->>'vote'<>'bordi' or r->>'name'<>'Number QA' or jsonb_array_length(r->'post_ids')<>1 then raise exception 'Second device did not restore profile'; end if;
 if r ? 'phone' or r ? 'token_hash' or r ? 'participant_hash' then raise exception 'Private fields exposed'; end if;
 perform public.tripcircle_participate(b,'vote',p_destination=>'jawhar');
 r:=public.tripcircle_participate(a,'me');
 if r->>'vote'<>'jawhar' then raise exception 'Vote not synchronized'; end if;
 perform public.tripcircle_number_login('0000000088',c,'Other QA');
 failed:=false;
 begin perform public.tripcircle_participate(c,'remove_post',p_post=>post_id); exception when others then failed:=true; end;
 if not failed then raise exception 'Other number removed post'; end if;
 perform public.tripcircle_participate(b,'remove_post',p_post=>post_id);
 perform public.tripcircle_participate(b,'logout');
 failed:=false;
 begin perform public.tripcircle_participate(b,'me'); exception when others then failed:=true; end;
 if not failed then raise exception 'Signed-out session still works'; end if;
 r:=public.tripcircle_participate(a,'me');
 if r->>'vote'<>'jawhar' then raise exception 'Logout affected other device'; end if;
 failed:=false;
 begin perform public.tripcircle_number_login('12345',gen_random_uuid()); exception when others then failed:=true; end;
 if not failed then raise exception 'Short phone accepted'; end if;
 failed:=false;
 begin perform public.tripcircle_number_login('abcdefghij',gen_random_uuid()); exception when others then failed:=true; end;
 if not failed then raise exception 'Non-digit phone accepted'; end if;
 failed:=false;
 begin perform 1 from tripcircle_private.number_profiles; exception when insufficient_privilege then failed:=true; end;
 if not failed then raise exception 'Private number lookup table exposed'; end if;
 begin
  if public.tripcircle_can_edit() then raise exception 'Number login grants organizer access'; end if;
 exception when insufficient_privilege then null; end;
end $$;
rollback;
