/// <reference types="vite/client" />
import React, {useEffect,useState} from 'react';
import {createClient, type Session} from '@supabase/supabase-js';
import {SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY} from './config';
import './style.css';
const db=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{storageKey:'tripcircle-auth'}});
type Photo={file:string;caption:string;author:string;source:string;license:string;license_url:string};
type Detail={photos:Photo[];spots:{name:string;summary:string}[];stays:{name:string;summary:string;url:string}[];gallery_url?:string};
type Destination={details?:Detail;id:string;name:string;landscape:string;journey:string;duration:string;summary:string;caveat:string;source_url:string;stay_url:string|null;itinerary:string;position:number};
type Plan={title:string;dates:string;notes:string};
type Participant={number_profile?:boolean;token:string;name:string;vote:string|null;post_ids:string[]};
type Post={id:string;name:string;kind:string;body:string;destination_id:string|null;created_at:string};
const participantKey='tripcircle-participant-v1';
function savedParticipant():Participant|null{try{const p=JSON.parse(localStorage.getItem(participantKey)||'null');return p&&typeof p.token==='string'&&typeof p.name==='string'?p:null}catch{return null}}

const safeLink=(s:string|null)=>{try{const u=new URL(s||'');return u.protocol==='https:'?u.href:null}catch{return null}};
export default function FriendsApp(){
 const [destinations,setDestinations]=useState<Destination[]>([]),[plan,setPlan]=useState<Plan|null>(null),[votes,setVotes]=useState<Record<string,number>>({}),[myVote,setMyVote]=useState<string|null>(null);
 const [participant,setParticipant]=useState<Participant|null>(savedParticipant),[posts,setPosts]=useState<Post[]>([]),[route,setRoute]=useState(window.location.hash);
 const [session,setSession]=useState<Session|null>(null),[editor,setEditor]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[filter,setFilter]=useState('All'),[authOpen,setAuthOpen]=useState(false),[editing,setEditing]=useState<Destination|null>(null),[editPlan,setEditPlan]=useState<Plan|null>(null),[busy,setBusy]=useState(false),[joinOpen,setJoinOpen]=useState(false),[nameNeeded,setNameNeeded]=useState(false),[joinPhone,setJoinPhone]=useState(''),[pendingVote,setPendingVote]=useState<string|null>(null);
 async function refresh(){
  const [d,p,v,c]=await Promise.all([db.from('tripcircle_destinations').select('*').order('position'),db.from('tripcircle_plan').select('*').eq('id',1).single(),db.rpc('tripcircle_vote_totals'),db.rpc('tripcircle_discussion_feed')]);
  if(d.error||p.error||v.error||c.error)throw new Error(d.error?.message||p.error?.message||v.error?.message||c.error?.message);
  setPosts(c.data||[]);setDestinations(d.data);setPlan(p.data);setVotes(Object.fromEntries((v.data||[]).map((r:{destination_id:string;votes:number})=>[r.destination_id,Number(r.votes)])));setError('');
 }
 useEffect(()=>{let stopped=false;const run=()=>refresh().catch(e=>{if(!stopped)setError(e.message)}).finally(()=>{if(!stopped)setLoading(false)});run();const timer=setInterval(run,20000);const focus=()=>run();window.addEventListener('focus',focus);db.auth.getSession().then(({data})=>{if(!stopped)setSession(data.session)});const {data}=db.auth.onAuthStateChange((_event,s)=>setSession(s));return()=>{stopped=true;clearInterval(timer);window.removeEventListener('focus',focus);data.subscription.unsubscribe()}},[]);
 useEffect(()=>{let stopped=false;setEditor(false);if(session){Promise.all([db.rpc('tripcircle_can_edit'),db.from('tripcircle_votes').select('destination_id').eq('user_id',session.user.id).maybeSingle()]).then(([e,v])=>{if(!stopped){setEditor(e.data===true);if(!savedParticipant())setMyVote(v.data?.destination_id||null);if(e.error||v.error)setError(e.error?.message||v.error?.message||'Could not load your permissions.')}})}return()=>{stopped=true}},[session?.user.id]);
 useEffect(()=>{const changed=()=>{setRoute(window.location.hash);window.scrollTo(0,0)};window.addEventListener('hashchange',changed);return()=>window.removeEventListener('hashchange',changed)},[]);
 useEffect(()=>{if(!authOpen&&!joinOpen&&!editing&&!editPlan)return;const esc=(e:KeyboardEvent)=>{if(e.key==='Escape'){setAuthOpen(false);setJoinOpen(false);setPendingVote(null);setEditing(null);setEditPlan(null)}};document.addEventListener('keydown',esc);return()=>document.removeEventListener('keydown',esc)},[authOpen,joinOpen,editing,editPlan]);
 function remember(p:Participant){localStorage.setItem(participantKey,JSON.stringify(p));setParticipant(p);setMyVote(p.vote)}
 useEffect(()=>{const p=savedParticipant();if(p)db.rpc('tripcircle_participate',{p_token:p.token,p_action:'me'}).then(({data,error})=>{if(savedParticipant()?.token!==p.token)return;if(error){setError('Your group profile could not be loaded. Join again to continue.');return}remember({...data,token:p.token})})},[]);
 function openJoin(id:string|null=null){setError('');setNameNeeded(false);setJoinPhone('');setPendingVote(id);setJoinOpen(true)}
 async function join(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);const token=crypto.randomUUID();try{const {data,error}=await db.rpc('tripcircle_number_login',{p_phone:joinPhone,p_token:token,p_name:nameNeeded?String(f.get('name')).trim():null});if(error)throw error;if(data.name_required){setNameNeeded(true);return}let p={...data,token};if(pendingVote){const r=await db.rpc('tripcircle_participate',{p_token:token,p_action:'vote',p_destination:p.vote===pendingVote?null:pendingVote});if(r.error)throw r.error;p={...r.data,token}}remember(p);setJoinOpen(false);setPendingVote(null);await refresh();setNotice(`Welcome, ${p.name}. Your group profile is saved.`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function leave(){if(!participant||busy)return;setBusy(true);try{const {error}=await db.rpc('tripcircle_participate',{p_token:participant.token,p_action:'logout'});if(error)throw error;localStorage.removeItem(participantKey);setParticipant(null);setMyVote(null);setNotice('Signed out. Use your number to return on any device.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function vote(id:string){if(!participant?.number_profile){openJoin(id);return}setBusy(true);try{const p=participant;const {data,error}=await db.rpc('tripcircle_participate',{p_token:p.token,p_action:'vote',p_destination:p.vote===id?null:id});if(error)throw error;remember({...data,token:p.token});await refresh();setNotice(p.vote===id?'Pick removed.':'Your pick is saved. Change it anytime.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function post(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!participant?.number_profile){openJoin();return}const form=e.currentTarget;setBusy(true);const f=new FormData(form);try{const p=participant;const {data,error}=await db.rpc('tripcircle_participate',{p_token:p.token,p_action:'post',p_kind:String(f.get('kind')),p_body:String(f.get('body')),p_destination:selected?.id||null});if(error)throw error;remember({...data,token:p.token});(form.elements.namedItem('body') as HTMLTextAreaElement).value='';await refresh();setNotice('Shared with the group.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function share(){try{await navigator.clipboard.writeText(window.location.href);setNotice('Link copied — paste it in WhatsApp.')}catch{setNotice('Copy the link from your address bar to share this place.')}}
 async function removePost(id:string){if(!participant)return;setBusy(true);try{const {data,error}=await db.rpc('tripcircle_participate',{p_token:participant.token,p_action:'remove_post',p_post:id});if(error)throw error;remember({...data,token:participant.token});await refresh();setNotice('Your post was removed.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function saveDestination(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;setBusy(true);const f=new FormData(e.currentTarget);const fields=['name','summary','journey','duration','caveat','itinerary','source_url','stay_url'];const update=Object.fromEntries(fields.map(k=>[k,f.get(k)||null]));try{const {data,error}=await db.from('tripcircle_destinations').update({...update,updated_at:new Date().toISOString()}).eq('id',editing.id).select('id');if(error)throw error;if(!data?.length)throw new Error('You do not have permission to edit this destination.');await refresh();setEditing(null);setNotice('Destination updated for everyone.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function savePlan(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{const {data,error}=await db.from('tripcircle_plan').update({title:f.get('title'),dates:f.get('dates'),notes:f.get('notes'),updated_at:new Date().toISOString()}).eq('id',1).select('id');if(error)throw error;if(!data?.length)throw new Error('You do not have permission to edit the plan.');await refresh();setEditPlan(null);setNotice('Plan saved for the group.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function auth(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{const {error}=await db.auth.signInWithPassword({email:String(f.get('email')),password:String(f.get('password'))});if(error)throw error;setAuthOpen(false);setNotice('Organizer signed in.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const selected=destinations.find(d=>route===`#place/${d.id}`)||null;
 const visiblePosts=selected?posts.filter(p=>p.destination_id===selected.id):posts;
 const photoUrl=(p:Photo)=>`${import.meta.env.BASE_URL}photos/${p.file}`;
 const mapUrl=(query:string)=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;
 const link=(url:string,label:string)=>safeLink(url)&&<a className="useful-link" href={safeLink(url)!} target="_blank" rel="noreferrer">{label} ↗</a>;
 const pick=(d:Destination)=><button className={myVote===d.id?'vote chosen':'vote'} disabled={busy} aria-pressed={myVote===d.id} onClick={()=>vote(d.id)}>{myVote===d.id?'✓ Your pick':'♡ Pick this'} <b>{votes[d.id]||0}</b></button>;
 return <><header><a href="#" className="brand"><span className="brandmark">△</span>TripCircle</a><div className="header-actions">{participant?.number_profile?<><span className="profile-name">Hi, {participant.name}</span><button className="text-button" disabled={busy} onClick={leave}>Log out</button></>:<button onClick={()=>openJoin()}>Join / Log in</button>}</div></header><main>
 {error&&<div role="alert" className="alert">{error}<button onClick={()=>refresh().catch(e=>setError(e.message))}>Retry</button></div>}{notice&&<div role="status" className="notice">{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}>×</button></div>}
 {selected?<><a href="#" className="back">← All places</a><div className="detail-heading"><div><p className="eyebrow">{selected.landscape} · FROM AHMEDABAD</p><h1>{selected.name}</h1><p className="subtitle">{selected.summary}</p></div><div className="detail-actions">{pick(selected)}<button onClick={share}>Share place</button>{editor&&<button onClick={()=>setEditing(selected)}>Edit</button>}</div></div>
 {selected.details?.photos?.length?<div className="gallery">{selected.details.photos.map(p=><figure key={p.file}><img src={photoUrl(p)} alt={p.caption}/><figcaption>{p.caption}</figcaption></figure>)}</div>:<div className="gallery-placeholder"><span>Forest days, slow mornings.</span><p>See authentic photos on the official tourism page.</p>{link(selected.details?.gallery_url||selected.source_url,'Open photo gallery')}</div>}
 <div className="detail-grid"><div><section className="detail-section"><p className="eyebrow">WHAT TO SEE</p><h2>Viewpoints & slow outings</h2><div className="spots">{selected.details?.spots?.map((p,i)=><article key={p.name}><span className="spot-number">0{i+1}</span><div><h3>{p.name}</h3><p>{p.summary}</p>{link(mapUrl(p.name+' '+selected.name),'Find on map')}</div></article>)}</div></section><section className="detail-section"><h2>A simple plan</h2><p className="preserve">{selected.itinerary}</p><p className="caveat">{selected.caveat}</p></section></div>
 <aside><section className="trip-facts"><span className="label">ONE WAY FROM AHMEDABAD</span><strong>{selected.journey}</strong><span className="label">TIME TO TAKE</span><strong>{selected.duration}</strong>{link(`https://www.google.com/maps/dir/?api=1&origin=Ahmedabad&destination=${encodeURIComponent(selected.name)}`,'Check the route')}</section><section className="detail-section stays"><p className="eyebrow">SMALL STAYS, NO RESORTS</p><h2>Where to stay</h2>{selected.details?.stays?.map(p=><article key={p.name}><h3>{p.name}</h3><p>{p.summary}</p>{link(p.url,'View stay / contact')}</article>)}<p className="small">Research leads, not bookings. Ask about rooms for 6–7, total price, meals and the location before paying.</p></section><section className="detail-section"><h2>Useful links</h2>{link(selected.source_url,'Tourism guide')}{link(mapUrl(selected.name),'Explore the area')}{selected.details?.gallery_url&&link(selected.details.gallery_url,'Official photo gallery')}</section></aside></div>
 {!!selected.details?.photos?.length&&<details className="credits"><summary>Photo credits & licences</summary>{selected.details.photos.map(p=><p key={p.file}>{p.caption} — {p.author}. <a href={safeLink(p.source)||undefined} target="_blank" rel="noreferrer">Original photo</a> · <a href={safeLink(p.license_url)||undefined} target="_blank" rel="noreferrer">{p.license}</a>. Images displayed cropped.</p>)}</details>}</>:<><div className="intro"><div><p className="eyebrow">AHMEDABAD · OCTOBER / NOVEMBER 2026</p><h1>{plan?.title||'Find our next quiet escape.'}</h1><p className="subtitle">Open a place. Explore the plan. Pick your favourite.</p></div><div className="trip-stamp"><b>6–7</b><span>friends</span><span>Small stays. No resorts.</span></div></div>
 <section className="simple-dates"><span>{plan?.dates||'Loading shared dates…'}</span>{editor&&plan&&<button className="text-button" onClick={()=>setEditPlan(plan)}>Edit plan</button>}</section><div className="section-top"><h2>Where shall we go?</h2><div className="filters" aria-label="Filter by landscape">{['All','Hills','Forest','Beach'].map(f=><button key={f} aria-pressed={filter===f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f}</button>)}</div></div>
 {loading?<p className="empty">Loading places…</p>:<div className="cards">{destinations.filter(d=>filter==='All'||d.landscape===filter).map(d=><article key={d.id} className="card"><a className="card-link" href={`#place/${d.id}`}>{d.details?.photos?.[0]?<img className="card-photo" src={photoUrl(d.details.photos[0])} alt={d.details.photos[0].caption} loading="lazy"/>:<div className="card-photo no-photo">A forest escape <span>Official photos inside ↗</span></div>}<div className="card-content"><span className="tag">{d.landscape}</span><h3>{d.name}</h3><p className="description">{d.summary}</p><p className="card-meta">{d.journey} · {d.duration}</p><span className="open-place">Explore this place →</span></div></a><div className="card-actions">{pick(d)}{editor&&<button className="text-button" onClick={()=>setEditing(d)}>Edit</button>}</div></article>)}</div>}</>}
 <section className="discussion" aria-label="Comments and suggestions"><div className="section-top"><div><p className="eyebrow">LET’S DECIDE TOGETHER</p><h2>{selected?`Thoughts on ${selected.name}?`:'Ideas from the group'}</h2></div></div>{participant?.number_profile?<form className="post-form" onSubmit={post}><p className="small">Posting as {participant.name}</p><div className="post-fields"><label>What are you sharing?<select name="kind"><option value="comment">A comment</option><option value="suggestion">A suggestion</option></select></label></div><label>Your message<textarea name="body" required maxLength={1500} placeholder="A question, another place, a better date…"/></label><button className="primary" disabled={busy}>{busy?'Sharing…':'Share idea'}</button><p className="small">Names and messages are public. Your number stays private.</p></form>:<div className="join-prompt"><p>Join with your name and number to share ideas and save your pick across devices.</p><button onClick={()=>openJoin()}>Join / Log in</button></div>}<div className="post-list">{visiblePosts.length===0?<p className="empty">No ideas yet. Share the first one.</p>:visiblePosts.map(p=><article className="post" key={p.id}><div className="post-heading"><strong>{p.name}</strong><span className="tag">{p.kind==='suggestion'?'Suggestion':'Comment'}</span><time dateTime={p.created_at}>{new Date(p.created_at).toLocaleString('en-IN',{day:'numeric',month:'short'})}</time></div>{p.destination_id&&!selected&&<a className="small post-topic" href={`#place/${p.destination_id}`}>{destinations.find(d=>d.id===p.destination_id)?.name}</a>}<p className="preserve">{p.body}</p>{participant?.post_ids?.includes(p.id)&&<button className="text-button" disabled={busy} onClick={()=>removePost(p.id)}>Remove my post</button>}</article>)}</div></section>
 {!selected&&<details className="group-notes"><summary>Before we book</summary><p className="preserve">{plan?.notes||'Choose a base, confirm the stay, then book transport.'}</p></details>}
 <footer><p>Researched 2 October 2026. Travel times are estimates; confirm stays and access. Use your number to return to the same profile on any device. Updates appear automatically.</p><div>{session?<><span>{editor?'Organizer':'Signed in'}</span><button className="text-button" onClick={async()=>{const {error}=await db.auth.signOut();if(error)setError(error.message)}}>Sign out</button></>:<button className="text-button" onClick={()=>setAuthOpen(true)}>Manage</button>}</div></footer></main>
 {(authOpen||joinOpen||editing||editPlan)&&<div className="modal-backdrop"><div role="dialog" aria-modal="true" aria-label={joinOpen?'Group login':authOpen?'Organizer login':editing?'Edit destination':'Edit trip'} className="modal"><button className="close" aria-label="Close dialog" onClick={()=>{setAuthOpen(false);setJoinOpen(false);setPendingVote(null);setEditing(null);setEditPlan(null)}}>×</button>{joinOpen&&<form onSubmit={join}><p className="eyebrow">WELCOME TO THE GROUP</p><h2>{nameNeeded?'What should we call you?':'Join / Log in'}</h2><p>{nameNeeded?'Add your name once. Next time, just enter your number.':'Enter your 10-digit number to open your saved profile.'}</p><label>Phone number<div className="phone-field"><span>+91</span><input autoFocus name="phone" type="tel" inputMode="numeric" autoComplete="tel-national" required pattern="[0-9]{10}" maxLength={10} value={joinPhone} onChange={e=>{setJoinPhone(e.target.value.replace(/[^0-9]/g,'').slice(0,10));setNameNeeded(false)}} placeholder="10-digit number"/></div></label>{nameNeeded&&<label>Your name<input autoFocus name="name" autoComplete="given-name" required minLength={2} maxLength={60}/></label>}<button className="primary" disabled={busy}>{busy?'Opening…':nameNeeded?'Save & join':'Continue'}</button><p className="small">No password or OTP. Anyone entering the same number can use this unverified group profile. Numbers are not shown publicly.</p></form>}{authOpen&&<AuthForm busy={busy} submit={auth}/>}
 {editing&&<form onSubmit={saveDestination}><h2>Edit {editing.name}</h2><p>Saved changes appear for everyone.</p>{(['name','journey','duration','summary','caveat','itinerary','source_url','stay_url'] as const).map(k=><label key={k}>{({name:'Place name',journey:'Journey estimate',duration:'Trip duration',summary:'Description',caveat:'Before booking',itinerary:'Itinerary',source_url:'Research link',stay_url:'Stay link'})[k]}{['summary','caveat','itinerary'].includes(k)?<textarea name={k} defaultValue={editing[k]||''} required maxLength={k==='itinerary'?2999:k==='summary'?1999:999}/>:<input name={k} type={k.endsWith('url')?'url':'text'} defaultValue={editing[k]||''} required={k!=='stay_url'} maxLength={k.endsWith('url')?2000:99}/>}</label>)}<button className="primary" disabled={busy}>{busy?'Saving…':'Save for everyone'}</button></form>}
 {editPlan&&<form onSubmit={savePlan}><h2>Edit the shared plan</h2><label>Trip title<input name="title" defaultValue={editPlan.title} required maxLength={119}/></label><label>Dates<input name="dates" defaultValue={editPlan.dates} required maxLength={199}/></label><label>Group notes<textarea name="notes" defaultValue={editPlan.notes} required maxLength={3999}/></label><button className="primary" disabled={busy}>{busy?'Saving…':'Save plan'}</button></form>}
 {error&&<p role="alert" className="alert">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}</div></div>}</>;
}
function AuthForm({busy,submit}:{busy:boolean;submit:(e:React.FormEvent<HTMLFormElement>)=>void}){return <form onSubmit={submit}><p className="eyebrow">ORGANIZER ACCESS</p><h2>Organizer login</h2><p>Only the organizer needs to sign in to edit the shared plan. Everyone can browse freely. A number-only group profile is used for picks and comments.</p><label>Email<input autoFocus name="email" type="email" autoComplete="email" required/></label><label>Password<input name="password" type="password" autoComplete="current-password" required minLength={8}/></label><button disabled={busy} className="primary">{busy?'Please wait…':'Sign in as organizer'}</button></form>}

