import React, {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient, type Session} from '@supabase/supabase-js';
import {SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY} from './config';
import './style.css';
const db=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{storageKey:'tripcircle-auth'}});
type Destination={id:string;name:string;landscape:string;journey:string;duration:string;summary:string;caveat:string;source_url:string;stay_url:string|null;itinerary:string;position:number};
type Plan={title:string;dates:string;notes:string};
const safeLink=(s:string|null)=>{try{const u=new URL(s||'');return u.protocol==='https:'?u.href:null}catch{return null}};
function App(){
 const [destinations,setDestinations]=useState<Destination[]>([]),[plan,setPlan]=useState<Plan|null>(null),[votes,setVotes]=useState<Record<string,number>>({}),[myVote,setMyVote]=useState<string|null>(null);
 const [session,setSession]=useState<Session|null>(null),[editor,setEditor]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[filter,setFilter]=useState('All'),[authOpen,setAuthOpen]=useState(false),[selected,setSelected]=useState<Destination|null>(null),[editing,setEditing]=useState<Destination|null>(null),[editPlan,setEditPlan]=useState<Plan|null>(null),[busy,setBusy]=useState(false);
 async function refresh(){
  const [d,p,v]=await Promise.all([db.from('tripcircle_destinations').select('*').order('position'),db.from('tripcircle_plan').select('*').eq('id',1).single(),db.rpc('tripcircle_vote_totals')]);
  if(d.error||p.error||v.error)throw new Error(d.error?.message||p.error?.message||v.error?.message);
  setDestinations(d.data);setPlan(p.data);setVotes(Object.fromEntries((v.data||[]).map((r:{destination_id:string;votes:number})=>[r.destination_id,Number(r.votes)])));setError('');
 }
 useEffect(()=>{let stopped=false;const run=()=>refresh().catch(e=>{if(!stopped)setError(e.message)}).finally(()=>{if(!stopped)setLoading(false)});run();const timer=setInterval(run,20000);const focus=()=>run();window.addEventListener('focus',focus);db.auth.getSession().then(({data})=>{if(!stopped)setSession(data.session)});const {data}=db.auth.onAuthStateChange((_event,s)=>setSession(s));return()=>{stopped=true;clearInterval(timer);window.removeEventListener('focus',focus);data.subscription.unsubscribe()}},[]);
 useEffect(()=>{let stopped=false;setEditor(false);setMyVote(null);if(session){Promise.all([db.rpc('tripcircle_can_edit'),db.from('tripcircle_votes').select('destination_id').eq('user_id',session.user.id).maybeSingle()]).then(([e,v])=>{if(!stopped){setEditor(e.data===true);setMyVote(v.data?.destination_id||null);if(e.error||v.error)setError(e.error?.message||v.error?.message||'Could not load your permissions.')}})}return()=>{stopped=true}},[session?.user.id]);
 useEffect(()=>{if(!authOpen&&!selected&&!editing&&!editPlan)return;const esc=(e:KeyboardEvent)=>{if(e.key==='Escape'){setAuthOpen(false);setSelected(null);setEditing(null);setEditPlan(null)}};document.addEventListener('keydown',esc);return()=>document.removeEventListener('keydown',esc)},[authOpen,selected,editing,editPlan]);
 async function vote(id:string){if(!session){setAuthOpen(true);return}setBusy(true);try{const {error}=myVote===id?await db.from('tripcircle_votes').delete().eq('user_id',session.user.id):await db.from('tripcircle_votes').upsert({user_id:session.user.id,destination_id:id,updated_at:new Date().toISOString()});if(error)throw error;setMyVote(myVote===id?null:id);await refresh();setNotice(myVote===id?'Vote removed.':'Your choice is saved. You can change it anytime.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function saveDestination(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;setBusy(true);const f=new FormData(e.currentTarget);const fields=['name','summary','journey','duration','caveat','itinerary','source_url','stay_url'];const update=Object.fromEntries(fields.map(k=>[k,f.get(k)||null]));try{const {data,error}=await db.from('tripcircle_destinations').update({...update,updated_at:new Date().toISOString()}).eq('id',editing.id).select('id');if(error)throw error;if(!data?.length)throw new Error('You do not have permission to edit this destination.');await refresh();setEditing(null);setNotice('Destination updated for everyone.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function savePlan(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{const {data,error}=await db.from('tripcircle_plan').update({title:f.get('title'),dates:f.get('dates'),notes:f.get('notes'),updated_at:new Date().toISOString()}).eq('id',1).select('id');if(error)throw error;if(!data?.length)throw new Error('You do not have permission to edit the plan.');await refresh();setEditPlan(null);setNotice('Plan saved for the group.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function auth(e:React.FormEvent<HTMLFormElement>,signup:boolean){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{const credentials={email:String(f.get('email')),password:String(f.get('password'))};const {data,error}=signup?await db.auth.signUp(credentials):await db.auth.signInWithPassword(credentials);if(error)throw error;if(signup&&!data.session){setNotice('Check your email to confirm your account, then return here and sign in. The confirmation link may open Relay.')}else{setAuthOpen(false);setNotice('Signed in.')}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const totalVotes=Object.values(votes).reduce((a,b)=>a+b,0);
 return <><header><a href="#" className="brand"><span className="brandmark">△</span>TripCircle</a><div className="header-actions">{editor&&<span className="role">Organizer</span>}{session?<button className="text-button" onClick={async()=>{const {error}=await db.auth.signOut();if(error)setError(error.message)}}>Sign out</button>:<button className="text-button" onClick={()=>setAuthOpen(true)}>Sign in to vote</button>}</div></header>
 <main><div className="intro"><div><p className="eyebrow">AHMEDABAD · OCTOBER / NOVEMBER 2026</p><h1>{plan?.title||'Find our next quiet escape.'}</h1><p className="subtitle">Less rush. More nature. A trip we choose together.</p></div><div className="trip-stamp"><b>6–7</b><span>friends</span><span>Private homestays<br/>No resorts</span></div></div>
 <section className="plan-strip" aria-label="Shared plan"><div><span className="label">DATES TO CONSIDER</span><strong>{plan?.dates||'Loading shared dates…'}</strong></div><div><span className="label">GROUP VOTES</span><strong>{totalVotes} {totalVotes===1?'friend has':'friends have'} voted</strong></div>{editor&&plan&&<button onClick={()=>setEditPlan(plan)}>Edit plan</button>}</section>
 {error&&<div role="alert" className="alert">{error}<button onClick={()=>refresh().catch(e=>setError(e.message))}>Retry</button></div>}{notice&&<div role="status" className="notice">{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}>×</button></div>}
 <div className="section-top"><h2>The shortlist <span>{destinations.length} places</span></h2><div className="filters" aria-label="Filter by landscape">{['All','Hills','Forest','Beach'].map(f=><button key={f} aria-pressed={filter===f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f}</button>)}</div></div>
 {loading?<p className="empty">Loading the shared shortlist…</p>:<div className="cards">{destinations.filter(d=>filter==='All'||d.landscape===filter).map((d,i)=><article key={d.id} className="card"><div className="card-top"><span className="number">{String(d.position).padStart(2,'0')}</span><span className="tag">{d.landscape}</span></div><h3>{d.name}</h3><p className="description">{d.summary}</p><div className="meta"><span><small>JOURNEY · ONE WAY</small>{d.journey}</span><span><small>TIME TO TAKE</small>{d.duration}</span></div><p className="caveat">{d.caveat}</p><div className="card-actions"><button className={myVote===d.id?'vote chosen':'vote'} disabled={busy} aria-pressed={myVote===d.id} onClick={()=>vote(d.id)}>{myVote===d.id?'✓ Your pick':'Vote for this'} <b>{votes[d.id]||0}</b></button><button className="text-button" onClick={()=>setSelected(d)}>Details</button>{editor&&<button className="text-button" onClick={()=>setEditing(d)}>Edit</button>}</div>{i===0&&filter==='All'&&<span className="recommendation">Our first recommendation</span>}</article>)}</div>}
 <section className="notes"><div><p className="eyebrow">BEFORE WE BOOK</p><h2>Keep the plan simple.</h2></div><p className="preserve">{plan?.notes||'Choose one base, confirm the stay, then book transport.'}</p></section>
 <footer><p>Research: 2 October 2026. Journey times are estimates. Stays and access are not confirmed. Shared data refreshes every 20 seconds.</p><span>TripCircle · Built for our group</span></footer></main>
 {(authOpen||selected||editing||editPlan)&&<div className="modal-backdrop"><div role="dialog" aria-modal="true" aria-label={authOpen?'Sign in':editing?'Edit destination':editPlan?'Edit trip':'Destination details'} className="modal"><button className="close" aria-label="Close dialog" onClick={()=>{setAuthOpen(false);setSelected(null);setEditing(null);setEditPlan(null)}}>×</button>
 {authOpen&&<AuthForm busy={busy} submit={auth}/>}
 {selected&&<><p className="eyebrow">{selected.landscape} · {selected.duration}</p><h2>{selected.name}</h2><p>{selected.summary}</p><h3>A slow itinerary</h3><p className="preserve">{selected.itinerary}</p><p className="caveat">{selected.caveat}</p>{safeLink(selected.source_url)&&<a className="external" href={safeLink(selected.source_url)!} target="_blank" rel="noreferrer">Read the research source</a>}{safeLink(selected.stay_url)&&<a className="external" href={safeLink(selected.stay_url)!} target="_blank" rel="noreferrer">Explore the homestay lead</a>}{selected.id==='guhagar'&&<a className="external" href="https://www.airbnb.com/rooms/28515160" target="_blank" rel="noreferrer">Koyari Vacation Home, Gimavi</a>}</>}
 {editing&&<form onSubmit={saveDestination}><h2>Edit {editing.name}</h2><p>Saved changes appear for everyone.</p>{(['name','journey','duration','summary','caveat','itinerary','source_url','stay_url'] as const).map(k=><label key={k}>{({name:'Place name',journey:'Journey estimate',duration:'Trip duration',summary:'Description',caveat:'Before booking',itinerary:'Itinerary',source_url:'Research link',stay_url:'Stay link'})[k]}{['summary','caveat','itinerary'].includes(k)?<textarea name={k} defaultValue={editing[k]||''} required maxLength={k==='itinerary'?2999:k==='summary'?1999:999}/>:<input name={k} type={k.endsWith('url')?'url':'text'} defaultValue={editing[k]||''} required={k!=='stay_url'} maxLength={k.endsWith('url')?2000:99}/>}</label>)}<button className="primary" disabled={busy}>{busy?'Saving…':'Save for everyone'}</button></form>}
 {editPlan&&<form onSubmit={savePlan}><h2>Edit the shared plan</h2><label>Trip title<input name="title" defaultValue={editPlan.title} required maxLength={119}/></label><label>Dates<input name="dates" defaultValue={editPlan.dates} required maxLength={199}/></label><label>Group notes<textarea name="notes" defaultValue={editPlan.notes} required maxLength={3999}/></label><button className="primary" disabled={busy}>{busy?'Saving…':'Save plan'}</button></form>}
 {error&&<p role="alert" className="alert">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}</div></div>}</>;
}
function AuthForm({busy,submit}:{busy:boolean;submit:(e:React.FormEvent<HTMLFormElement>,signup:boolean)=>void}){const [signup,setSignup]=useState(false);return <form onSubmit={e=>submit(e,signup)}><p className="eyebrow">YOUR GROUP CHOICE</p><h2>{signup?'Create an account':'Sign in'}</h2><p>Anyone can read the shortlist. Sign in to save one vote; only the organizer can edit the plan.</p><label>Email<input autoFocus name="email" type="email" autoComplete="email" required/></label><label>Password<input name="password" type="password" autoComplete={signup?'new-password':'current-password'} required minLength={8}/></label><button disabled={busy} className="primary">{busy?'Please wait…':signup?'Create account':'Sign in'}</button><button type="button" className="text-button" onClick={()=>setSignup(!signup)}>{signup?'Already have an account? Sign in':'New here? Create an account'}</button>{signup&&<p className="small">Confirm your email before signing in. Accounts use the shared Relay authentication service.</p>}</form>}
createRoot(document.getElementById('root')!).render(<App/>);
