import React, {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient, type Session} from '@supabase/supabase-js';
import {SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY} from './config';
import './style.css';
const db=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{storageKey:'tripcircle-auth'}});
type Destination={id:string;name:string;landscape:string;journey:string;duration:string;summary:string;caveat:string;source_url:string;stay_url:string|null;itinerary:string;position:number};
type Plan={title:string;dates:string;notes:string};
type Participant={token:string;name:string;vote:string|null;post_ids:string[]};
type Post={id:string;name:string;kind:string;body:string;destination_id:string|null;created_at:string};
const participantKey='tripcircle-participant-v1';
function savedParticipant():Participant|null{try{const p=JSON.parse(localStorage.getItem(participantKey)||'null');return p&&typeof p.token==='string'&&typeof p.name==='string'?p:null}catch{return null}}

const safeLink=(s:string|null)=>{try{const u=new URL(s||'');return u.protocol==='https:'?u.href:null}catch{return null}};
function App(){
 const [destinations,setDestinations]=useState<Destination[]>([]),[plan,setPlan]=useState<Plan|null>(null),[votes,setVotes]=useState<Record<string,number>>({}),[myVote,setMyVote]=useState<string|null>(null);
 const [participant,setParticipant]=useState<Participant|null>(savedParticipant),[posts,setPosts]=useState<Post[]>([]),[joinOpen,setJoinOpen]=useState(false);
 const [session,setSession]=useState<Session|null>(null),[editor,setEditor]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[filter,setFilter]=useState('All'),[authOpen,setAuthOpen]=useState(false),[selected,setSelected]=useState<Destination|null>(null),[editing,setEditing]=useState<Destination|null>(null),[editPlan,setEditPlan]=useState<Plan|null>(null),[busy,setBusy]=useState(false);
 async function refresh(){
  const [d,p,v,c]=await Promise.all([db.from('tripcircle_destinations').select('*').order('position'),db.from('tripcircle_plan').select('*').eq('id',1).single(),db.rpc('tripcircle_vote_totals'),db.rpc('tripcircle_discussion_feed')]);
  if(d.error||p.error||v.error||c.error)throw new Error(d.error?.message||p.error?.message||v.error?.message||c.error?.message);
  setPosts(c.data||[]);setDestinations(d.data);setPlan(p.data);setVotes(Object.fromEntries((v.data||[]).map((r:{destination_id:string;votes:number})=>[r.destination_id,Number(r.votes)])));setError('');
 }
 useEffect(()=>{let stopped=false;const run=()=>refresh().catch(e=>{if(!stopped)setError(e.message)}).finally(()=>{if(!stopped)setLoading(false)});run();const timer=setInterval(run,20000);const focus=()=>run();window.addEventListener('focus',focus);db.auth.getSession().then(({data})=>{if(!stopped)setSession(data.session)});const {data}=db.auth.onAuthStateChange((_event,s)=>setSession(s));return()=>{stopped=true;clearInterval(timer);window.removeEventListener('focus',focus);data.subscription.unsubscribe()}},[]);
 useEffect(()=>{let stopped=false;setEditor(false);if(session){Promise.all([db.rpc('tripcircle_can_edit'),db.from('tripcircle_votes').select('destination_id').eq('user_id',session.user.id).maybeSingle()]).then(([e,v])=>{if(!stopped){setEditor(e.data===true);if(!savedParticipant())setMyVote(v.data?.destination_id||null);if(e.error||v.error)setError(e.error?.message||v.error?.message||'Could not load your permissions.')}})}return()=>{stopped=true}},[session?.user.id]);
 useEffect(()=>{if(!authOpen&&!joinOpen&&!selected&&!editing&&!editPlan)return;const esc=(e:KeyboardEvent)=>{if(e.key==='Escape'){setAuthOpen(false);setJoinOpen(false);setSelected(null);setEditing(null);setEditPlan(null)}};document.addEventListener('keydown',esc);return()=>document.removeEventListener('keydown',esc)},[authOpen,joinOpen,selected,editing,editPlan]);
 function remember(p:Participant){localStorage.setItem(participantKey,JSON.stringify(p));setParticipant(p);setMyVote(p.vote)}
 useEffect(()=>{const p=savedParticipant();if(p)db.rpc('tripcircle_participate',{p_token:p.token,p_action:'me'}).then(({data,error})=>{if(savedParticipant()?.token!==p.token)return;if(error){setError('Your group profile could not be loaded. Join again to continue.');return}remember({...data,token:p.token})})},[]);
 async function join(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{const token=participant?.token||crypto.randomUUID();const raw=String(f.get('phone')).replace(/[\s()-]/g,'');const phone=/^[6-9][0-9]{9}$/.test(raw)?'+91'+raw:raw;const {data,error}=await db.rpc('tripcircle_participate',{p_token:token,p_action:'join',p_name:String(f.get('name')).trim(),p_phone:phone});if(error)throw error;remember({...data,token});setJoinOpen(false);setNotice('You joined the group. Pick a trip and share your ideas.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function vote(id:string){if(!participant){setJoinOpen(true);return}setBusy(true);try{const {data,error}=await db.rpc('tripcircle_participate',{p_token:participant.token,p_action:'vote',p_destination:myVote===id?null:id});if(error)throw error;remember({...data,token:participant.token});await refresh();setNotice(myVote===id?'Vote removed.':'Your choice is saved. You can change it anytime.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function post(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!participant){setJoinOpen(true);return}const form=e.currentTarget;setBusy(true);const f=new FormData(form);try{const {data,error}=await db.rpc('tripcircle_participate',{p_token:participant.token,p_action:'post',p_kind:String(f.get('kind')),p_body:String(f.get('body')),p_destination:f.get('destination')||null});if(error)throw error;remember({...data,token:participant.token});form.reset();await refresh();setNotice('Posted for the group.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function removePost(id:string){if(!participant)return;setBusy(true);try{const {data,error}=await db.rpc('tripcircle_participate',{p_token:participant.token,p_action:'remove_post',p_post:id});if(error)throw error;remember({...data,token:participant.token});await refresh();setNotice('Your post was removed.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function saveDestination(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;setBusy(true);const f=new FormData(e.currentTarget);const fields=['name','summary','journey','duration','caveat','itinerary','source_url','stay_url'];const update=Object.fromEntries(fields.map(k=>[k,f.get(k)||null]));try{const {data,error}=await db.from('tripcircle_destinations').update({...update,updated_at:new Date().toISOString()}).eq('id',editing.id).select('id');if(error)throw error;if(!data?.length)throw new Error('You do not have permission to edit this destination.');await refresh();setEditing(null);setNotice('Destination updated for everyone.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function savePlan(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{const {data,error}=await db.from('tripcircle_plan').update({title:f.get('title'),dates:f.get('dates'),notes:f.get('notes'),updated_at:new Date().toISOString()}).eq('id',1).select('id');if(error)throw error;if(!data?.length)throw new Error('You do not have permission to edit the plan.');await refresh();setEditPlan(null);setNotice('Plan saved for the group.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function auth(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{const {error}=await db.auth.signInWithPassword({email:String(f.get('email')),password:String(f.get('password'))});if(error)throw error;setAuthOpen(false);setNotice('Organizer signed in.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const totalVotes=Object.values(votes).reduce((a,b)=>a+b,0);
 return <><header><a href="#" className="brand"><span className="brandmark">△</span>TripCircle</a><div className="header-actions">{editor&&<span className="role">Organizer</span>}{participant?<button className="text-button" onClick={()=>setJoinOpen(true)}>{participant.name}</button>:<button className="text-button" onClick={()=>setJoinOpen(true)}>Join the group</button>}{participant&&<button disabled={busy} className="text-button" onClick={()=>{localStorage.removeItem(participantKey);setParticipant(null);setMyVote(null);setNotice('Profile forgotten on this device. Your saved vote and posts remain.')}}>Forget profile</button>}{session?<button className="text-button" onClick={async()=>{const {error}=await db.auth.signOut();if(error)setError(error.message)}}>Sign out</button>:<button className="text-button" onClick={()=>setAuthOpen(true)}>Organizer login</button>}</div></header>
 <main><div className="intro"><div><p className="eyebrow">AHMEDABAD · OCTOBER / NOVEMBER 2026</p><h1>{plan?.title||'Find our next quiet escape.'}</h1><p className="subtitle">Less rush. More nature. A trip we choose together.</p></div><div className="trip-stamp"><b>6–7</b><span>friends</span><span>Private homestays<br/>No resorts</span></div></div>
 <section className="plan-strip" aria-label="Shared plan"><div><span className="label">DATES TO CONSIDER</span><strong>{plan?.dates||'Loading shared dates…'}</strong></div><div><span className="label">GROUP VOTES</span><strong>{totalVotes} {totalVotes===1?'friend has':'friends have'} voted</strong></div>{editor&&plan&&<button onClick={()=>setEditPlan(plan)}>Edit plan</button>}</section>
 {error&&<div role="alert" className="alert">{error}<button onClick={()=>refresh().catch(e=>setError(e.message))}>Retry</button></div>}{notice&&<div role="status" className="notice">{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}>×</button></div>}
 <div className="section-top"><h2>The shortlist <span>{destinations.length} places</span></h2><div className="filters" aria-label="Filter by landscape">{['All','Hills','Forest','Beach'].map(f=><button key={f} aria-pressed={filter===f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f}</button>)}</div></div>
 {loading?<p className="empty">Loading the shared shortlist…</p>:<div className="cards">{destinations.filter(d=>filter==='All'||d.landscape===filter).map((d,i)=><article key={d.id} className="card"><div className="card-top"><span className="number">{String(d.position).padStart(2,'0')}</span><span className="tag">{d.landscape}</span></div><h3>{d.name}</h3><p className="description">{d.summary}</p><div className="meta"><span><small>JOURNEY · ONE WAY</small>{d.journey}</span><span><small>TIME TO TAKE</small>{d.duration}</span></div><p className="caveat">{d.caveat}</p><div className="card-actions"><button className={myVote===d.id?'vote chosen':'vote'} disabled={busy} aria-pressed={myVote===d.id} onClick={()=>vote(d.id)}>{myVote===d.id?'✓ Your pick':'Vote for this'} <b>{votes[d.id]||0}</b></button><button className="text-button" onClick={()=>setSelected(d)}>Details</button>{editor&&<button className="text-button" onClick={()=>setEditing(d)}>Edit</button>}</div>{i===0&&filter==='All'&&<span className="recommendation">Our first recommendation</span>}</article>)}</div>}
 <section className="discussion" aria-label="Comments and suggestions"><div className="section-top"><div><p className="eyebrow">LET’S DECIDE TOGETHER</p><h2>Comments & suggestions</h2></div>{!participant&&<button onClick={()=>setJoinOpen(true)}>Join to share an idea</button>}</div><p className="discussion-intro">Suggest another peaceful place, ask about a stay, or tell us what works for you. Names and posts are visible to anyone with this public link.</p>{participant&&<form className="post-form" onSubmit={post}><div className="post-fields"><label>Post type<select name="kind"><option value="comment">Comment</option><option value="suggestion">Suggestion</option></select></label><label>About<select name="destination"><option value="">The whole trip</option>{destinations.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div><label>Your message<textarea name="body" required maxLength={1500} placeholder="A quiet place, a better date, a question…"/></label><p className="small">Posting as {participant.name}. Please keep phone numbers and personal details out of your message.</p><button className="primary" disabled={busy}>{busy?'Saving…':'Share with the group'}</button></form>}<div className="post-list">{posts.length===0?<p className="empty">No ideas yet. Start the conversation.</p>:posts.map(p=><article className="post" key={p.id}><div className="post-heading"><strong>{p.name}</strong><span className="tag">{p.kind==='suggestion'?'Suggestion':'Comment'}</span><time dateTime={p.created_at}>{new Date(p.created_at).toLocaleString('en-IN',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</time></div>{p.destination_id&&<p className="small post-topic">{destinations.find(d=>d.id===p.destination_id)?.name}</p>}<p className="preserve">{p.body}</p>{participant?.post_ids?.includes(p.id)&&<button className="text-button" disabled={busy} onClick={()=>removePost(p.id)}>Remove my post</button>}</article>)}</div></section>
 <section className="notes"><div><p className="eyebrow">BEFORE WE BOOK</p><h2>Keep the plan simple.</h2></div><p className="preserve">{plan?.notes||'Choose one base, confirm the stay, then book transport.'}</p></section>
 <footer><p>Research: 2 October 2026. Journey times are estimates. Stays and access are not confirmed. Shared data refreshes every 20 seconds.</p><span>TripCircle · Built for our group</span></footer></main>
 {(authOpen||joinOpen||selected||editing||editPlan)&&<div className="modal-backdrop"><div role="dialog" aria-modal="true" aria-label={joinOpen?'Join the group':authOpen?'Organizer login':editing?'Edit destination':editPlan?'Edit trip':'Destination details'} className="modal"><button className="close" aria-label="Close dialog" onClick={()=>{setAuthOpen(false);setJoinOpen(false);setSelected(null);setEditing(null);setEditPlan(null)}}>×</button>
 {joinOpen&&<form onSubmit={join}><p className="eyebrow">YOUR GROUP PROFILE</p><h2>{participant?'Update your profile':'Join the group'}</h2><p>Just your name and phone number. No email, password or verification link.</p><label>Name<input autoFocus name="name" autoComplete="name" required minLength={2} maxLength={60} defaultValue={participant?.name||''}/></label><label>Phone number<input name="phone" type="tel" autoComplete="tel" required maxLength={20} placeholder="10-digit Indian number or +country code"/></label><p className="small">Your name appears beside posts. Your phone stays private and is self-reported, not verified. This browser remembers your profile; another device starts a new one.</p><button className="primary" disabled={busy}>{busy?'Saving…':participant?'Save profile':'Join the group'}</button></form>}{authOpen&&<AuthForm busy={busy} submit={auth}/>}
 {selected&&<><p className="eyebrow">{selected.landscape} · {selected.duration}</p><h2>{selected.name}</h2><p>{selected.summary}</p><h3>A slow itinerary</h3><p className="preserve">{selected.itinerary}</p><p className="caveat">{selected.caveat}</p>{safeLink(selected.source_url)&&<a className="external" href={safeLink(selected.source_url)!} target="_blank" rel="noreferrer">Read the research source</a>}{safeLink(selected.stay_url)&&<a className="external" href={safeLink(selected.stay_url)!} target="_blank" rel="noreferrer">Explore the homestay lead</a>}{selected.id==='guhagar'&&<a className="external" href="https://www.airbnb.com/rooms/28515160" target="_blank" rel="noreferrer">Koyari Vacation Home, Gimavi</a>}</>}
 {editing&&<form onSubmit={saveDestination}><h2>Edit {editing.name}</h2><p>Saved changes appear for everyone.</p>{(['name','journey','duration','summary','caveat','itinerary','source_url','stay_url'] as const).map(k=><label key={k}>{({name:'Place name',journey:'Journey estimate',duration:'Trip duration',summary:'Description',caveat:'Before booking',itinerary:'Itinerary',source_url:'Research link',stay_url:'Stay link'})[k]}{['summary','caveat','itinerary'].includes(k)?<textarea name={k} defaultValue={editing[k]||''} required maxLength={k==='itinerary'?2999:k==='summary'?1999:999}/>:<input name={k} type={k.endsWith('url')?'url':'text'} defaultValue={editing[k]||''} required={k!=='stay_url'} maxLength={k.endsWith('url')?2000:99}/>}</label>)}<button className="primary" disabled={busy}>{busy?'Saving…':'Save for everyone'}</button></form>}
 {editPlan&&<form onSubmit={savePlan}><h2>Edit the shared plan</h2><label>Trip title<input name="title" defaultValue={editPlan.title} required maxLength={119}/></label><label>Dates<input name="dates" defaultValue={editPlan.dates} required maxLength={199}/></label><label>Group notes<textarea name="notes" defaultValue={editPlan.notes} required maxLength={3999}/></label><button className="primary" disabled={busy}>{busy?'Saving…':'Save plan'}</button></form>}
 {error&&<p role="alert" className="alert">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}</div></div>}</>;
}
function AuthForm({busy,submit}:{busy:boolean;submit:(e:React.FormEvent<HTMLFormElement>)=>void}){return <form onSubmit={submit}><p className="eyebrow">ORGANIZER ACCESS</p><h2>Organizer login</h2><p>Group members use name and phone. Editing the shared plan still requires the verified organizer account.</p><label>Email<input autoFocus name="email" type="email" autoComplete="email" required/></label><label>Password<input name="password" type="password" autoComplete="current-password" required minLength={8}/></label><button disabled={busy} className="primary">{busy?'Please wait…':'Sign in as organizer'}</button></form>}
createRoot(document.getElementById('root')!).render(<App/>);
